# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracepad < Formula
  desc "LLM observability and evals in a single binary"
  homepage "https://github.com/tracepad/tracepad"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.2/tracepad_0.1.2_darwin_amd64.tar.gz"
      sha256 "694a198fba54795e8d27b21fe8d124af422b3fb388c0e562869ba73e0b867ae6"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.2/tracepad_0.1.2_darwin_arm64.tar.gz"
      sha256 "96ba91910d8ad5730eda4d1ba7bfd97df8b18cc2e185ba86d9921c93752a4976"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.2/tracepad_0.1.2_linux_amd64.tar.gz"
      sha256 "d307242ed8072f35fccefe66005ba613ca321b877db275ac0d60d6fe8ddb8b6f"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.2/tracepad_0.1.2_linux_arm64.tar.gz"
      sha256 "256c0e54b55bec6d7f7b71d6d002a180088bca08138a974cb18fbfcd9e980576"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracepad version")
  end
end
