# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracepad < Formula
  desc "LLM observability and evals in a single binary"
  homepage "https://github.com/tracepad/tracepad"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.3/tracepad_0.1.3_darwin_amd64.tar.gz"
      sha256 "5a62aec2d34986ae7f8ea448f0c48f29a696f8df7532a92342a90523512f539d"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.3/tracepad_0.1.3_darwin_arm64.tar.gz"
      sha256 "a5a1a3c16915cb85217602213c375404fa7e0ca03fe04ab159764e55700c5427"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.3/tracepad_0.1.3_linux_amd64.tar.gz"
      sha256 "f45028db6e8a573656b5a1c2a3947dd63c71505a0854291a7d51de59d4e6c84c"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.3/tracepad_0.1.3_linux_arm64.tar.gz"
      sha256 "ce49da934b347e65e8ab776ed9af81b583cabe314b576118537070cd9d5d49df"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracepad version")
  end
end
