# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracepad < Formula
  desc "LLM observability and evals in a single binary"
  homepage "https://github.com/tracepad/tracepad"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.1/tracepad_0.1.1_darwin_amd64.tar.gz"
      sha256 "382245181df919b4f6f3ffc130ff295fbd7f0378b19b291c4524c8cf2bfb092b"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.1/tracepad_0.1.1_darwin_arm64.tar.gz"
      sha256 "94d6a0b60771f63afd0162e6534c615038d6785f9738167d509503266d4a212f"

      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.1/tracepad_0.1.1_linux_amd64.tar.gz"
      sha256 "16d22d966e028e3919911f9893b85003f690a72fadcadfa62f5447e0819caf9f"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracepad/tracepad/releases/download/v0.1.1/tracepad_0.1.1_linux_arm64.tar.gz"
      sha256 "3a4aca66f30441e6141ddc1a4c2bb0aa6d5f44d9a3e9ee1f480750fecbb1266b"
      define_method(:install) do
        bin.install "tracepad"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracepad version")
  end
end
